#! /bin/sh

sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor DVI-I-0 -d I II III
bspc monitor HDMI-0 -d IV V VI


bspc config border_width          0
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^4'
bspc rule -a Caprine desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a jetbrains-pycharm desktop='^2'
